apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-0-5b
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: gguf
      runtime: llama-cpp-server
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 1Gi
